	PROCESSOR	P16F887
	INCLUDE		<P16F887.INC>

	__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
	__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)
	
VC5		EQU			0x20
VC6		EQU			0x21
VC7		EQU			0x22
VPA		EQU			0x23	
VX		EQU			0x24

		ORG			0x00
		BANKSEL		ANSEL
		MOVLW		0x03
		MOVWF		ANSEL
		CLRF		ANSELH
		
		BANKSEL		TRISA
		MOVLW		0xFF
		MOVWF		TRISA
		CLRF		TRISB
		CLRF		TRISC
		CLRF		TRISD
		CLRF		TRISE
		CLRF		ADCON1
		
		BANKSEL		PORTA
C_P		

LPA		MOVF		PORTA,W
		MOVWF		VPA
		MOVF		VPA,F
		BTFSC		STATUS,Z
		GOTO		CA5
		GOTO		LPA

		MOVLW		0xD5
		MOVWF		ADCON0
EAD5	BSF			ADCON0,GO_DONE
		BTFSC		ADCON0,GO_DONE
		GOTO 		EAD5
		MOVF		ADRESH,W
		MOVWF		VC5
		BCF			ADCON0,ADON
		

		MOVF		VC5,W
		MOVWF		PORTB
		GOTO		C_P


F8R		MOVWF		VX
		MOVF		VX,W
		SUBLW		0x20
		BTFSC		STATUS,C
		GOTO		R_1
		MOVF		VX,W
		SUBLW		0x40
		BTFSC		STATUS,C
		GOTO		R_2
		MOVF		VX,W
		SUBLW		0x60
		BTFSC		STATUS,C
		GOTO		R_3
		MOVF		VX,W
		SUBLW		0x80
		BTFSC		STATUS,C
		GOTO		R_4
		MOVF		VX,W
		SUBLW		0xA0
		BTFSC		STATUS,C
		GOTO		R_5
		MOVF		VX,W
		SUBLW		0xC0
		BTFSC		STATUS,C
		GOTO		R_6
		MOVF		VX,W
		SUBLW		0xE0
		BTFSC		STATUS,C
		GOTO		R_7
		RETLW		0xFF
R_7		RETLW		0x7F
R_6		RETLW		0x3F
R_5		RETLW		0x1F
R_4		RETLW		0x0F
R_3		RETLW		0x07
R_2		RETLW		0x03
R_1		RETLW		0x01

F5R		MOVWF		VX
		MOVF		VX,W
		SUBLW		0x33
		BTFSC		STATUS,C
		GOTO		R_11
		MOVF		VX,W
		SUBLW		0x66
		BTFSC		STATUS,C
		GOTO		R_22
		MOVF		VX,W
		SUBLW		0x99
		BTFSC		STATUS,C
		GOTO		R_33
		MOVF		VX,W
		SUBLW		0xCC
		BTFSC		STATUS,C
		GOTO		R_44
		RETLW		0xFF
R_44	RETLW		0xC0
R_33	RETLW		0x30
R_22	RETLW		0x0C
R_11	RETLW		0x03

		END