	PROCESSOR	P16F887
	INCLUDE		<P16F887.INC>

	__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
	__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)
	
VAC6	EQU			0x21	
VX		EQU			0x24
CA6		EQU			0x25
CT0		EQU			0x22

		ORG			0x00
		BANKSEL		ANSEL
		MOVLW		0x40
		MOVWF		ANSEL
		CLRF		ANSELH
		
		BANKSEL		TRISA
		MOVLW		0x20
		MOVWF		TRISA
		CLRF		TRISB
		MOVLW		0x18
		MOVWF		TRISC
		CLRF		TRISD
		MOVLW		0x02		
		MOVWF		TRISE
		CLRF		ADCON1
		MOVLW		0x40
		MOVWF		SSPSTAT
		
		BANKSEL		PORTA
		MOVLW		0x34
		MOVWF		SSPCON
C_P		
		
		MOVLW		0xD9
		MOVWF		ADCON0
		BSF			ADCON0,GO_DONE
EAD5	BTFSC		ADCON0,GO_DONE
		GOTO 		EAD5
		MOVF		ADRESH,W
		MOVWF		VAC6
		BCF			ADCON0,ADON
			
		BANKSEL		TRISA
EBF		BTFSS		SSPSTAT,BF
		GOTO 		EBF

		BANKSEL		PORTA
		MOVF		SSPBUF,W
		MOVWF		PORTB
		MOVF		VAC6,W
		MOVWF		SSPBUF

		GOTO		C_P


F8R		MOVWF		VX
		MOVF		VX,W
		SUBLW		0x20
		BTFSC		STATUS,C
		GOTO		R_1
		MOVF		VX,W
		SUBLW		0x40
		BTFSC		STATUS,C
		GOTO		R_2
		MOVF		VX,W
		SUBLW		0x60
		BTFSC		STATUS,C
		GOTO		R_3
		MOVF		VX,W
		SUBLW		0x80
		BTFSC		STATUS,C
		GOTO		R_4
		MOVF		VX,W
		SUBLW		0xA0
		BTFSC		STATUS,C
		GOTO		R_5
		MOVF		VX,W
		SUBLW		0xC0
		BTFSC		STATUS,C
		GOTO		R_6
		MOVF		VX,W
		SUBLW		0xE0
		BTFSC		STATUS,C
		GOTO		R_7
		RETLW		0xFF
R_7		RETLW		0x7F
R_6		RETLW		0x3F
R_5		RETLW		0x1F
R_4		RETLW		0x0F
R_3		RETLW		0x07
R_2		RETLW		0x03
R_1		RETLW		0x01

F5R		MOVWF		VX
		MOVF		VX,W
		SUBLW		0x33
		BTFSC		STATUS,C
		GOTO		R_11
		MOVF		VX,W
		SUBLW		0x66
		BTFSC		STATUS,C
		GOTO		R_22
		MOVF		VX,W
		SUBLW		0x99
		BTFSC		STATUS,C
		GOTO		R_33
		MOVF		VX,W
		SUBLW		0xCC
		BTFSC		STATUS,C
		GOTO		R_44
		RETLW		0xFF
R_44	RETLW		0xC0
R_33	RETLW		0x30
R_22	RETLW		0x0C
R_11	RETLW		0x03

RS
		MOVLW	0x02
		MOVWF	CT0	
CIT0S	CLRF	TMR0
E64S	BTFSS	TMR0,1
		GOTO	E64S
		DECFSZ	CT0,F

		END