	PROCESSOR	P16F887
	INCLUDE		<P16F887.INC>

	__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
	__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)
	
VAC6		EQU			0x21	
V1			EQU			0x24
V2			EQU			0x25
VAC5		EQU			0x22

			ORG			0x00

		BANKSEL		ANSEL
		MOVLW		0x60
		MOVWF		ANSEL
		CLRF		ANSELH
		
		BANKSEL		TRISA
		MOVLW		0x20
		MOVWF		TRISA
		CLRF		TRISB
		MOVLW		0x18
		MOVWF		TRISC
		CLRF		TRISD
		MOVLW		0x07		
		MOVWF		TRISE
		CLRF		ADCON1
		MOVLW		0x40
		MOVWF		SSPSTAT
		
		BANKSEL		PORTA
		MOVLW		0x34
		MOVWF		SSPCON
C_P		
		
		MOVLW		0xD9		
		MOVWF		ADCON0		;CONFIGURO EL ADC Y LO INICIO
		BSF			ADCON0,GO_DONE	;INDICO QUE INICIE LA CONVERSION
EAD5	BTFSC		ADCON0,GO_DONE	;VERIFICO SI YA ACABO LA CONVERSION
		GOTO 		EAD5			;NO, ESPERO
		MOVF		ADRESH,W		;SI, GUARDO EL RESULTADO EN W
		MOVWF		VAC5			;GUARDO W EN VAC6
		BCF			ADCON0,ADON		;APAGO EL ADC
;-------------------------------
		MOVLW		0xD5		
		MOVWF		ADCON0		;CONFIGURO EL ADC Y LO INICIO
		BSF			ADCON0,GO_DONE	;INDICO QUE INICIE LA CONVERSION
EAD1	BTFSC		ADCON0,GO_DONE	;VERIFICO SI YA ACABO LA CONVERSION
		GOTO 		EAD1			;NO, ESPERO
		MOVF		ADRESH,W		;SI, GUARDO EL RESULTADO EN W
		MOVWF		VAC6			;GUARDO W EN VAC6
		BCF			ADCON0,ADON		;APAGO EL ADC
;------------SERIAL			
		BANKSEL		TRISA			;CAMBIO DE BANCO		
EBF		BTFSS		SSPSTAT,BF		;VERIFICO SI EL DATO TERMINO DE TRANSMITIRSE
		GOTO 		EBF				;NO, ESPERO

		BANKSEL		PORTA			;SI, CAMBIO DE BANCO
		MOVF		SSPBUF,W		;MUEVO EL DATO1 RECIBIDO A W
		MOVWF		V1			;MUEVO W AL PUERTO B
		MOVF		VAC5,W			;MUEVO RL RESULTADO DEL ADC A W
		MOVWF		SSPBUF			;TRANSMITO EL DATO2 (ADC)

		BANKSEL		TRISA			;CAMBIO DE BANCO		
EBF1	BTFSS		SSPSTAT,BF		;VERIFICO SI EL DATO TERMINO DE TRANSMITIRSE
		GOTO 		EBF1			;NO, ESPERO

		BANKSEL		PORTA			;SI, CAMBIO DE BANCO
		MOVF		SSPBUF,W		;MUEVO EL DATO1 RECIBIDO A W
		MOVWF		V2			;MUEVO W AL PUERTO B
		MOVF		VAC6,W			;MUEVO RL RESULTADO DEL ADC A W
		MOVWF		SSPBUF			;TRANSMITO EL DATO2 (ADC)

		BTFSS		PORTE,RE2
		GOTO		P1
		GOTO		P2
P1		MOVF		V1,W
		MOVWF		PORTB
		GOTO		C_P
P2		MOVF		V2,W
		MOVWF		PORTB
		GOTO		C_P

		END