	PROCESSOR	P16F887
	INCLUDE		<P16F887.INC>

	__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
	__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)
	
	
	ORG			0x00
	BANKSEL		ANSEL
	MOVLW		0x0F
	MOVWF		ANSEL
	CLRF		ANSELH
	CLRF		SRCON
	
	BANKSEL		CM1CON0
	MOVLW		0xA0
	MOVWF		CM1CON0
	MOVLW		0xA1	
	MOVWF		CM2CON0
	MOVLW		0x02
	MOVWF		CM2CON1
	
	BANKSEL		VRCON
	CLRF		VRCON
	MOVLW		0x0F
	MOVWF		TRISA
	
C_P
	GOTO		C_P	
	END