	PROCESSOR	P16F887
	INCLUDE		<P16F887.INC>

	__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
	__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)
	

CT0		EQU			0x21
	
		ORG			0x00
		GOTO		INI
		ORG			0x04
		GOTO		SAI
	
INI		ORG			0x05	
		BANKSEL		ANSEL
		CLRF		ANSEL
		CLRF		ANSELH
		
		BANKSEL		TRISA
		CLRF		TRISA
		MOVLW		0xF1
		MOVWF		TRISB
		MOVLW		0xF0
		MOVWF		IOCB
		CLRF		TRISC
		CLRF		TRISD
		CLRF		TRISE
		MOVLW		0xD6
		MOVWF		OPTION_REG
		
		BANKSEL		PORTA
		MOVLW		0x98
		MOVWF		INTCON
		CLRF		PORTE
	
C_P		
		GOTO		C_P
	
SAI		BTFSC		INTCON,INTF
		GOTO		PARAR
		CLRF		PORTB
		BCF			INTCON,RBIF
ALA		
		BSF			PORTE,RE0
		BCF			PORTE,RE1
		CALL		RETA
		BCF			PORTE,RE0
		BSF			PORTE,RE1
		CALL		RETA
		GOTO		ALA
PARAR	
		CLRF		PORTE
		BCF			INTCON,INTF
		GOTO		C_P
		
RETA	MOVLW 	  	0x21
		MOVWF		CT0	
CIT0S	CLRF		TMR0
E64S	BTFSS		TMR0,7
		GOTO		E64S
		DECFSZ		CT0,F
		GOTO		CIT0S
		RETURN

		END