	PROCESSOR	P16F887
	INCLUDE		<P16F887.INC>

	__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
	__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)
	
VA0		EQU			0x21
VA1		EQU			0x22	
VX		EQU			0x23

		ORG			0x00
		BANKSEL		ANSEL
		MOVLW		0xFF
		MOVWF		ANSEL
		CLRF		ANSELH
		
		BANKSEL		TRISA
		CLRF		TRISA
		CLRF		TRISB
		CLRF		TRISC
		CLRF		TRISD
		MOVLW		0x07
		MOVWF		TRISE
		MOVLW		0xD6
		MOVWF		OPTION_REG
		CLRF		ADCON1
		
		BANKSEL		PORTA
C_P		
		CALL 		RT
		MOVLW		0xD9
		MOVWF		ADCON0
EA1		BSF			ADCON0,GO_DONE
		BTFSC		ADCON0,GO_DONE
		GOTO 		EA1
		MOVF		ADRESH,W
		MOVWF		VA0
		BCF			ADCON0,ADON
		MOVF		VA0,W
		CALL		F8R
		MOVWF		PORTB
		CALL RT
		MOVLW		0xDD
		MOVWF		ADCON0
EA2		BSF			ADCON0,GO_DONE
		BTFSC		ADCON0,GO_DONE
		GOTO 		EA2
		MOVF		ADRESH,W
		MOVWF		VA1
		BCF			ADCON0,ADON
		MOVF		VA1,W
		CALL		F8RR
		MOVWF		PORTC
		CALL 		RT		
		CLRF		VA0
		CLRF		VA1
		GOTO		C_P


F8R		MOVWF		VX
		MOVF		VX,W
		SUBLW		0x20
		BTFSC		STATUS,C
		GOTO		R_1
		MOVF		VX,W
		SUBLW		0x40
		BTFSC		STATUS,C
		GOTO		R_2
		MOVF		VX,W
		SUBLW		0x60
		BTFSC		STATUS,C
		GOTO		R_3
		MOVF		VX,W
		SUBLW		0x80
		BTFSC		STATUS,C
		GOTO		R_4
		MOVF		VX,W
		SUBLW		0xA0
		BTFSC		STATUS,C
		GOTO		R_5
		MOVF		VX,W
		SUBLW		0xC0
		BTFSC		STATUS,C
		GOTO		R_6
		MOVF		VX,W
		SUBLW		0xE0
		BTFSC		STATUS,C
		GOTO		R_7
		RETLW		0x80
R_7		RETLW		0x40
R_6		RETLW		0x20
R_5		RETLW		0x10
R_4		RETLW		0x08
R_3		RETLW		0x04
R_2		RETLW		0x02
R_1		RETLW		0x01


F8RR	MOVWF		VX
		MOVF		VX,W
		SUBLW		0x20
		BTFSC		STATUS,C
		GOTO		R_11
		MOVF		VX,W
		SUBLW		0x40
		BTFSC		STATUS,C
		GOTO		R_22
		MOVF		VX,W
		SUBLW		0x60
		BTFSC		STATUS,C
		GOTO		R_33
		MOVF		VX,W
		SUBLW		0x80
		BTFSC		STATUS,C
		GOTO		R_44
		MOVF		VX,W
		SUBLW		0xA0
		BTFSC		STATUS,C
		GOTO		R_55
		MOVF		VX,W
		SUBLW		0xC0
		BTFSC		STATUS,C
		GOTO		R_66
		MOVF		VX,W
		SUBLW		0xE0
		BTFSC		STATUS,C
		GOTO		R_77
		RETLW		0x7F
R_77	RETLW		0xBF
R_66	RETLW		0xDF
R_55	RETLW		0xEF
R_44	RETLW		0xF7
R_33	RETLW		0xFB
R_22	RETLW		0xFD
R_11	RETLW		0xFE


F5R		MOVWF		VX
		MOVF		VX,W
		SUBLW		0x33
		BTFSC		STATUS,C
		GOTO		R_111
		MOVF		VX,W
		SUBLW		0x66
		BTFSC		STATUS,C
		GOTO		R_222
		MOVF		VX,W
		SUBLW		0x99
		BTFSC		STATUS,C
		GOTO		R_333
		MOVF		VX,W
		SUBLW		0xCC
		BTFSC		STATUS,C
		GOTO		R_444
		RETLW		0xFF
R_444	RETLW		0xC0
R_333	RETLW		0x30
R_222	RETLW		0x0C
R_111	RETLW		0x03


RT
		CLRF	TMR0
E64I	BTFSS	TMR0,6
		GOTO	E64I
		RETURN

		END