	PROCESSOR	P16F887
	INCLUDE		<P16F887.INC>

	__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
	__CONFIG _CONFIG2, (_WRT_OFF & _BOR40V)
	
VC5		EQU			0x20
XPD		EQU			0X22
XPU		EQU			0x23
XU		EQU			0x24
VPA		EQU			0x25	
VX		EQU			0x26


C_P		ORG			0x00
		BANKSEL		ANSEL
		MOVLW		0x01
		MOVWF		ANSEL
		CLRF		ANSELH
		
		BANKSEL		TRISA
		MOVLW		0x01
		MOVWF		TRISA
		CLRF		TRISB
		CLRF		TRISC
		CLRF		TRISD
		CLRF		TRISE
		MOVLW		0xD6
		MOVWF		OPTION_REG		
		BANKSEL		ADCON1
		CLRF		ADCON1
		BANKSEL		PORTA
		MOVLW		0xC1
		MOVWF		ADCON0
		
	
	
EAD5	BSF			ADCON0,GO_DONE
		BTFSC		ADCON0,GO_DONE
		GOTO 		EAD5
		MOVF		ADRESH,W
		MOVWF		VC5
	;	BCF			PIR1,ADIF
		MOVWF		VC5
		MOVLW		0x01
		MOVWF		PORTC
		MOVF		VC5,W
		MOVWF		PORTB
		CALL        R4MS
		CLRF		VC5
		GOTO		C_P

R4MS
		CLRF	TMR0
E6		BTFSS	TMR0,5
		GOTO	E6
		RETURN

		END